name: base
channels:
  - Conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.1
  - python=3.8.8
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - pip
  - pip:
   - pandas
   - matplotlib
   - numpy
   - scipy
  
  
